version: '3.x'
services:
  eureka-service:
    image: 'storoom_eureka:latest'
    build:
      context: eureka
    container_name: eureka-service
    ports:
      - "8761:8761"
    environment:
      SERVER_PORT: 8761

  gateway:
    image: 'storoom_gateway:latest'
    build:
      context: gateway
    container_name: gateway
    depends_on:
      - eureka-service
    ports:
      - "8080:8080"
    environment:
      server.port: 8080
      eureka.client.service-url.defaultZone: http://eureka-service:8761/eureka


  token:
    image: 'storoom_token:latest'
    build:
      context: token
    container_name: token
    depends_on:
      - eureka-service
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      eureka.client.service-url.defaultZone: http://eureka-service:8761/eureka

  db:
    image: 'postgres:14.5'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: compose-postgres
      POSTGRES_PASSWORD: compose-postgres

secrets:
  private.key:
    file: ./private.key
  public.key:
    file: ./public.key