version: '3.x'
services:
  app:
    image: 'storoom:latest'
    build:
      context: ..
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
#        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/compose-postgres
      SPRING_DATASOURCE_USERNAME: compose-postgres
      SPRING_DATASOURCE_PASSWORD: compose-postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      PUBLIC_JWT_KEY_PATH: file:/run/secrets/public.key
      PRIVATE_JWT_KEY_PATH: file:/run/secrets/private.key
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin

    secrets:
      - public.key
      - private.key

  db:
    image: 'postgres:14.5'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: compose-postgres
      POSTGRES_PASSWORD: compose-postgres
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
#      interval: 1s
#      timeout: 1s
#      retries: 5

secrets:
  private.key:
    file: ./private.key
  public.key:
    file: ./public.key