delete from orders where true;
delete from users where true;
delete from units where true;
delete from locks where true;
delete from manufacturers where true;
delete from locations where true;
delete from owners_locations where true;
delete from owners where true;
delete from companies where true;
