openapi: 3.0.1
info:
  title: Store room
  version: v1
servers:
  - url: http://localhost:8080
    description: Gateway url
paths: {}
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    basicAuth:
      type: http
      scheme: basic