openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8081
    description: Generated server url
paths:
  /token:
    post:
      tags:
        - token-controller
      operationId: token
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
      security:
        - basicAuth: []
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

