scrape_configs:
  - job_name: pushgateway
    scrape_interval: 5s
    static_configs:
      - targets:
          - pushgateway:9091
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - cadvisor:8080